// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package store

import (
	"context"

	"github.com/sqlc-dev/pqtype"
)

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_log (release_id, actor, action, detail)
VALUES ($1, $2, $3, $4)
RETURNING id, release_id, actor, action, detail, created_at
`

type InsertAuditEntryParams struct {
	ReleaseID string                `db:"release_id" json:"release_id"`
	Actor     string                `db:"actor" json:"actor"`
	Action    string                `db:"action" json:"action"`
	Detail    pqtype.NullRawMessage `db:"detail" json:"detail"`
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error) {
	row := q.db.QueryRowContext(ctx, insertAuditEntry,
		arg.ReleaseID,
		arg.Actor,
		arg.Action,
		arg.Detail,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.Actor,
		&i.Action,
		&i.Detail,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditEntriesByRelease = `-- name: ListAuditEntriesByRelease :many
SELECT id, release_id, actor, action, detail, created_at
FROM audit_log
WHERE release_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAuditEntriesByRelease(ctx context.Context, releaseID string) ([]AuditLog, error) {
	rows, err := q.db.QueryContext(ctx, listAuditEntriesByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.Actor,
			&i.Action,
			&i.Detail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
