// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: environments.sql

package store

import (
	"context"
)

const getEnvironment = `-- name: GetEnvironment :one
SELECT id, release_id, env_name, status, deployed_at
FROM release_environments
WHERE release_id = $1 AND env_name = $2
`

type GetEnvironmentParams struct {
	ReleaseID string `db:"release_id" json:"release_id"`
	EnvName   string `db:"env_name" json:"env_name"`
}

func (q *Queries) GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRowContext(ctx, getEnvironment, arg.ReleaseID, arg.EnvName)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvName,
		&i.Status,
		&i.DeployedAt,
	)
	return i, err
}

const listEnvironmentsByRelease = `-- name: ListEnvironmentsByRelease :many
SELECT id, release_id, env_name, status, deployed_at
FROM release_environments
WHERE release_id = $1
ORDER BY env_name
`

func (q *Queries) ListEnvironmentsByRelease(ctx context.Context, releaseID string) ([]ReleaseEnvironment, error) {
	rows, err := q.db.QueryContext(ctx, listEnvironmentsByRelease, releaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReleaseEnvironment
	for rows.Next() {
		var i ReleaseEnvironment
		if err := rows.Scan(
			&i.ID,
			&i.ReleaseID,
			&i.EnvName,
			&i.Status,
			&i.DeployedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO release_environments (release_id, env_name, status)
VALUES ($1, $2, $3)
ON CONFLICT (release_id, env_name)
DO UPDATE SET status = EXCLUDED.status, deployed_at = CASE
    WHEN EXCLUDED.status = 'deployed' THEN now()
    ELSE release_environments.deployed_at
END
RETURNING id, release_id, env_name, status, deployed_at
`

type UpsertEnvironmentParams struct {
	ReleaseID string    `db:"release_id" json:"release_id"`
	EnvName   string    `db:"env_name" json:"env_name"`
	Status    EnvStatus `db:"status" json:"status"`
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (ReleaseEnvironment, error) {
	row := q.db.QueryRowContext(ctx, upsertEnvironment, arg.ReleaseID, arg.EnvName, arg.Status)
	var i ReleaseEnvironment
	err := row.Scan(
		&i.ID,
		&i.ReleaseID,
		&i.EnvName,
		&i.Status,
		&i.DeployedAt,
	)
	return i, err
}
