// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type EnvStatus string

const (
	EnvStatusPending   EnvStatus = "pending"
	EnvStatusDeploying EnvStatus = "deploying"
	EnvStatusDeployed  EnvStatus = "deployed"
	EnvStatusFailed    EnvStatus = "failed"
	EnvStatusBlocked   EnvStatus = "blocked"
)

func (e *EnvStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EnvStatus(s)
	case string:
		*e = EnvStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EnvStatus: %T", src)
	}
	return nil
}

type NullEnvStatus struct {
	EnvStatus EnvStatus `json:"env_status"`
	Valid     bool      `json:"valid"` // Valid is true if EnvStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEnvStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EnvStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EnvStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEnvStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EnvStatus), nil
}

type ReleaseStatus string

const (
	ReleaseStatusDraft    ReleaseStatus = "draft"
	ReleaseStatusRunning  ReleaseStatus = "running"
	ReleaseStatusDeployed ReleaseStatus = "deployed"
	ReleaseStatusFailed   ReleaseStatus = "failed"
)

func (e *ReleaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReleaseStatus(s)
	case string:
		*e = ReleaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReleaseStatus: %T", src)
	}
	return nil
}

type NullReleaseStatus struct {
	ReleaseStatus ReleaseStatus `json:"release_status"`
	Valid         bool          `json:"valid"` // Valid is true if ReleaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReleaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReleaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReleaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReleaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReleaseStatus), nil
}

type AuditLog struct {
	ID        uuid.UUID             `db:"id" json:"id"`
	ReleaseID string                `db:"release_id" json:"release_id"`
	Actor     string                `db:"actor" json:"actor"`
	Action    string                `db:"action" json:"action"`
	Detail    pqtype.NullRawMessage `db:"detail" json:"detail"`
	CreatedAt time.Time             `db:"created_at" json:"created_at"`
}

type Release struct {
	ID        string        `db:"id" json:"id"`
	Service   string        `db:"service" json:"service"`
	Version   string        `db:"version" json:"version"`
	Status    ReleaseStatus `db:"status" json:"status"`
	CreatedAt time.Time     `db:"created_at" json:"created_at"`
	UpdatedAt time.Time     `db:"updated_at" json:"updated_at"`
}

type ReleaseEnvironment struct {
	ID         uuid.UUID    `db:"id" json:"id"`
	ReleaseID  string       `db:"release_id" json:"release_id"`
	EnvName    string       `db:"env_name" json:"env_name"`
	Status     EnvStatus    `db:"status" json:"status"`
	DeployedAt sql.NullTime `db:"deployed_at" json:"deployed_at"`
}
