// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	CountReleasesByService(ctx context.Context, service string) (int64, error)
	CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error)
	GetEnvironment(ctx context.Context, arg GetEnvironmentParams) (ReleaseEnvironment, error)
	GetRelease(ctx context.Context, id string) (Release, error)
	InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditLog, error)
	ListAuditEntriesByRelease(ctx context.Context, releaseID string) ([]AuditLog, error)
	ListEnvironmentsByRelease(ctx context.Context, releaseID string) ([]ReleaseEnvironment, error)
	ListReleases(ctx context.Context, arg ListReleasesParams) ([]Release, error)
	UpdateReleaseStatus(ctx context.Context, arg UpdateReleaseStatusParams) (Release, error)
	UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (ReleaseEnvironment, error)
}

var _ Querier = (*Queries)(nil)
