// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package store

import (
	"context"
)

const countReleasesByService = `-- name: CountReleasesByService :one
SELECT count(*) FROM releases WHERE service = $1
`

func (q *Queries) CountReleasesByService(ctx context.Context, service string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReleasesByService, service)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (id, service, version, status)
VALUES ($1, $2, $3, 'draft')
RETURNING id, service, version, status, created_at, updated_at
`

type CreateReleaseParams struct {
	ID      string `db:"id" json:"id"`
	Service string `db:"service" json:"service"`
	Version string `db:"version" json:"version"`
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, createRelease, arg.ID, arg.Service, arg.Version)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, service, version, status, created_at, updated_at
FROM releases
WHERE id = $1
`

func (q *Queries) GetRelease(ctx context.Context, id string) (Release, error) {
	row := q.db.QueryRowContext(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReleases = `-- name: ListReleases :many
SELECT id, service, version, status, created_at, updated_at
FROM releases
WHERE service = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListReleasesParams struct {
	Service string `db:"service" json:"service"`
	Limit   int32  `db:"limit" json:"limit"`
	Offset  int32  `db:"offset" json:"offset"`
}

func (q *Queries) ListReleases(ctx context.Context, arg ListReleasesParams) ([]Release, error) {
	rows, err := q.db.QueryContext(ctx, listReleases, arg.Service, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.Service,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateReleaseStatus = `-- name: UpdateReleaseStatus :one
UPDATE releases
SET status = $2, updated_at = now()
WHERE id = $1
RETURNING id, service, version, status, created_at, updated_at
`

type UpdateReleaseStatusParams struct {
	ID     string        `db:"id" json:"id"`
	Status ReleaseStatus `db:"status" json:"status"`
}

func (q *Queries) UpdateReleaseStatus(ctx context.Context, arg UpdateReleaseStatusParams) (Release, error) {
	row := q.db.QueryRowContext(ctx, updateReleaseStatus, arg.ID, arg.Status)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.Service,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
